file_format: "1"
id: microdox
name: Microdox
type: shield
url: https://boardsource.xyz/products/crab-broom-choc-ferris-sweep
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - sweep_left
  - sweep_right
